name: "check-open-prs"
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
